// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const get = `-- name: Get :one
SELECT id, balance
FROM app.wallets
WHERE id = $1
`

func (q *Queries) Get(ctx context.Context, id pgtype.UUID) (AppWallet, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i AppWallet
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const getForUpdate = `-- name: GetForUpdate :one
SELECT id, balance
FROM app.wallets
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetForUpdate(ctx context.Context, id pgtype.UUID) (AppWallet, error) {
	row := q.db.QueryRow(ctx, getForUpdate, id)
	var i AppWallet
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const update = `-- name: Update :one
UPDATE app.wallets
SET balance = $2
WHERE id = $1
RETURNING id, balance
`

type UpdateParams struct {
	ID      pgtype.UUID
	Balance int64
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (AppWallet, error) {
	row := q.db.QueryRow(ctx, update, arg.ID, arg.Balance)
	var i AppWallet
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}
