// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const get = `-- name: Get :one
SELECT id, balance
FROM wallets
WHERE id = $1
`

func (q *Queries) Get(ctx context.Context, id pgtype.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i Wallet
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const getForUpdate = `-- name: GetForUpdate :one
SELECT id, balance
FROM wallets
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetForUpdate(ctx context.Context, id pgtype.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getForUpdate, id)
	var i Wallet
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const update = `-- name: Update :exec
UPDATE wallets
SET balance = $2
WHERE id = $1
`

type UpdateParams struct {
	ID      pgtype.UUID
	Balance int64
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update, arg.ID, arg.Balance)
	return err
}
